const CONSTANTS = {
  EVENT_USERS_LOADING: 'EVENT_USERS_LOADING',
  EVENT_USERS_ERROR: 'EVENT_USERS_ERROR',
  EVENT_USERS_RECEIVED_USERS: 'EVENT_USERS_RECEIVED_USERS',
  EVENT_USERS_UPDATE_USER: 'EVENT_USERS_UPDATE_USER',
  EVENT_USERS_INSERT_USER: 'EVENT_USERS_INSERT_USER',
  EVENT_USERS_PAYMENT_UPDATE: 'EVENT_USERS_PAYMENT_UPDATE',
  EVENT_USERS_PAYMENT_INSERT: 'EVENT_USERS_PAYMENT_INSERT',
  EVENT_USERS_DELETE_USER: 'EVENT_USERS_DELETE_USER',
  EVENTS_LOADING: 'EVENTS_LOADING',
  EVENTS_ERROR: 'EVENTS_ERROR',
  EVENTS_RECEIVED_EVENTS: 'EVENTS_RECEIVED_EVENTS',
  EVENTS_UPDATE_EVENT: 'EVENTS_UPDATE_EVENT',
  EVENTS_INSERT_EVENT: 'EVENTS_INSERT_EVENT',
  EVENTS_DELETE_EVENT: 'EVENTS_DELETE_EVENT'
};

export default CONSTANTS;
